image:
  pullSecrets:
    - name: registry.creatio.com

# gs-web-api pods settings.
webApi:
  # Endpoint description
  # See https://kubernetes.io/docs/concepts/services-networking/service/ for more details.
  service:
    # NodePort or LoadBalancer or enable ingress below
    type: NodePort
    # Uncomment line below if need use static port
    # nodePort: 32020
  env:
    # Ignored indexing entities list. Not available entities in global search.
    ignoredEntities: VwSysProcessLog,SysPrcHistoryLog,MLModel,MLModelFile,SysSettings,VwWebServiceV2

# gs-web-indexing-service pods settings.
webIndexingService:
  # Endpoint description
  # See https://kubernetes.io/docs/concepts/services-networking/service/ for more details.
  service:
    # NodePort or LoadBalancer or enable ingress below
    type: NodePort
    # Uncomment line below if need use static port
    # nodePort: 32021
  # Ingress endpoint settings (optional)
  # See https://kubernetes.io/docs/concepts/services-networking/ingress/ for more details.

# gs-search-service pods settings.
searchService:
  # Endpoint description
  # See https://kubernetes.io/docs/concepts/services-networking/service/ for more details.
  service:
    # NodePort or LoadBalancer or enable ingress below
    type: NodePort
    nodePort: 30332

# Log4Net settings
log4Net:
  level: ERROR

# Multi pods global parameters
global:
  incrementDays: 500

  # Elastic search parameters
  elasticsearch:
    url: https://gs-elasticsearch:9200
    user: elastic
    password: elastic
    tls:
      enable: true

  identityProvider:
    url: ""
    useOAuth: false

  # Search service external url
  searchService:
    # For example: http://k8s-master-node:30332
    url: <YOUR_SEARCH_SERVICE_EXTERNAL_URL>
  # Web api external url
  webApi:
    # For example: http://k8s-master-node:32020
    url: <YOUR_WEB_API_EXTERNAL_URL>

  # RabbitMQ connection parameters
  rabbitmq:
    host: rabbitmq
    vhost: /
    port: 5672
    user: gs
    password: gs

  # Global search database connection parameters
  db:
    user: postgres
    password: password
    database: postgres
    host: postgresql
    port: 5432

  # Redis server connection parameters
  redis:
    host: redis-master
    port: 6379
    database: 1

# Redis deployment settings
# For more details see https://github.com/helm/charts/blob/master/stable/redis/values.yaml
redis:
  enabled: true
  fullnameOverride: redis
  usePassword: false
  master:
    persistence:
      enabled: true
      size: 1Gi
#      storageClass: dynamic-pvc
    resources:
      requests:
        memory: 128Mi
        cpu: 70m
      limits:
        memory: 256Mi
        cpu: 70m
  cluster:
    enabled: false

# RabbitMQ deployment settings
# For more details see https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml
rabbitmq:
  enabled: true
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  resources:
    requests:
      memory: 1024Mi
      cpu: 300m
    limits:
      memory: 1024Mi
      cpu: 300m
  fullnameOverride: rabbitmq
  auth:
    username: gs
    password: gs
  persistence:
    enabled: true
    size: 1Gi
#    storageClass: dynamic-pvc
  clustering:
    enabled: false
  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "rabbitmq-0"
        - "rabbitmq-0.rabbitmq-headless.globalsearch.svc.cluster.local"

# PostgreSQL deployment settings
# For more details see https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml
postgresql:
  enabled: true
  fullnameOverride: postgresql
  persistence:
    enabled: true
    size: 2Gi
#    storageClass: dynamic-pvc
  resources:
    requests:
      memory: 128Mi
      cpu: 200m
    limits:
      memory: 512Mi
      cpu: 300m
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: postgres
  postgresqlConfiguration:
    listen_addresses : "'*'"
    port : 5432
    wal_level : "'hot_standby'"
    fsync : "'on'"
    max_wal_size : "'400MB'"
    max_wal_senders : 16
    wal_keep_segments : 12
    hot_standby : "'on'"
    include_dir : "'conf.d'"
    max_connections: 1024
  initdbScripts:
    init.sql: |
      CREATE DATABASE globalsearch;
      GRANT ALL PRIVILEGES ON DATABASE globalsearch TO postgres;

# Elasticsearch deployment settings
# For more details see https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml
elasticsearch:
  enabled: true
  master:
    masterOnly: false
    persistence:
      enabled: true
  security:
    enabled: true
    elasticPassword: elastic
    tls:
      restEncryption: true
      autoGenerated: true
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

#  service:
#    type: NodePort
#    nodePorts:
#      restAPI: 30162
